### ISSUE TITLE
Waiting for the code

### ISSUE THREAD

**Issue by wujunnan0929** [Delay-Xili/SDNet#1]
We are all looking forward to you,**xixi**. Do not **Delay**, plz. **:)**

**Comment by qgh1223** [comment]
Also looking forward to your code

**Comment by Delay-Xili** [comment]
![download](https://user-images.githubusercontent.com/22764459/201481419-4a86155e-980d-4726-ac7e-68372dbf0ed6.jpeg)

**Comment by whilelistking** [comment]
This is a very interesting invention and I feel it has generational significance, so I think I need to study your code in detail and actively await your open source.

**Comment by shm-coder** [comment]
期待

**Comment by shm-coder** [comment]
Also looking forward to codes. Thanks

**Comment by scaler2017** [comment]
Also looking forward to codes. Thanks

**Comment by tsb0601** [comment]
Sorry ICLR rebuttal and CVPR are busier than we expected. We are hoping to release the code asap after the deadlines....

**Comment by Delay-Xili** [comment]
@tsb0601 Thanks peter,

We are sorry for the delay. The ICLR rebuttal and CVPR submission are busier than we expected, and we will release our code before 1st Dec. 

Thank you for being patience.

**Comment by liuyiming199721** [comment]
您好，作者什么时候发布代码谢谢您，今天已经12月1号了。

**Comment by liuyiming199721** [comment]
Hello, when will the author release the code? Thank you. It is already December 1st today.

**Comment by dzy258** [comment]
估计是又延期了吧，我也在等这个，每天都看一遍是不是发布了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Delay-Xili/SDNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)





 
您好，作者什么时候发布代码谢谢您，今天已经12月1号了。

**Comment by liuyiming199721** [comment]
老哥，您也是做可解释的，想和您交个朋友。


眼镜蛇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Delay-Xili/SDNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)





 估计是又延期了吧，我也在等这个，每天都看一遍是不是发布了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Delay-Xili/SDNet"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年12月1日(星期四) 晚上9:36 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 
 
 
 
 
 
   
 您好，作者什么时候发布代码谢谢您，今天已经12月1号了。

**Comment by YZ20211221** [comment]
> 老哥，您也是做可解释的，想和您交个朋友。 眼镜蛇 ***@***.*** &bsp;
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Delay-Xili/SDNet" ***@***.***&gt;; 发送时间:&nbsp;2022年12月1日(星期四) 晚上9:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 估计是又延期了吧，我也在等这个，每天都看一遍是不是发布了
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "Delay-Xili/SDNet" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2022年12月1日(星期四) 晚上9:36 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 您好，作者什么时候发布代码谢谢您，今天已经12月1号了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

同做可解释性，可以一起交流

**Comment by YZ20211221** [comment]
> 我的wx是15176678823
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Dec 2, 2022 15:43 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 老哥，您也是做可解释的，想和您交个朋友。 眼镜蛇 @.*** &amp;bsp; ... ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Delay-Xili/SDNet" @.&gt;; 发送时间:&nbsp;2022年12月1日(星期四) 晚上9:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 估计是又延期了吧，我也在等这个，每天都看一遍是不是发布了 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "Delay-Xili/SDNet" @.&amp;gt;; 发送时间:&amp;nbsp;2022年12月1日(星期四) 晚上9:36 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 您好，作者什么时候发布代码谢谢您，今天已经12月1号了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 同做可解释性，可以一起交流 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

加您了，您没同意？

**Comment by liuyiming199721** [comment]
您好，我这里没有显示请留下您的



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 3, 2022 20:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)




  
我的wx是15176678823
 …
 ---Original--- From: @.&gt; Date: Fri, Dec 2, 2022 15:43 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 老哥，您也是做可解释的，想和您交个朋友。 眼镜蛇 @.*** &amp;bsp; ... ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Delay-Xili/SDNet" @.&gt;; 发送时间:&nbsp;2022年12月1日(星期四) 晚上9:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 估计是又延期了吧，我也在等这个，每天都看一遍是不是发布了 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "Delay-Xili/SDNet" @.&amp;gt;; 发送时间:&amp;nbsp;2022年12月1日(星期四) 晚上9:36 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 您好，作者什么时候发布代码谢谢您，今天已经12月1号了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 同做可解释性，可以一起交流 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
加您了，您没同意？

**Comment by Love666sJane** [comment]
同期待源码

**Comment by Love666sJane** [comment]
每日一看是否开源

**Comment by liuyiming199721** [comment]
哈哈哈



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 11, 2023 12:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)




 
每日一看是否开源

**Comment by liuyiming199721** [comment]
要不要交个朋友



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 11, 2023 12:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)




 
同期待源码

**Comment by Cet101** [comment]
研究了一段时间，想看看FISTA的具体细节

**Comment by liuyiming199721** [comment]
一起交流呀，我已经搭建了一个模型。



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 6, 2023 21:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)




 
研究了一段时间，想看看FISTA的具体细节

**Comment by Cet101** [comment]
> 一起交流呀，我已经搭建了一个模型。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Feb 6, 2023 21:04 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1) 研究了一段时间，想看看FISTA的具体细节 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

嗯嗯，我加你vx了，也可加我qq614464503，请多指教

**Comment by OneIsAll-w** [comment]
Also looking forward to codes, thanks.

**Comment by li-xinlin** [comment]
Looking forward to the codes.

**Comment by liuyiming199721** [comment]
你是老外？



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 28, 2023 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)




 
Looking forward to the codes.

**Comment by liuyiming199721** [comment]
你是中国人嘛？





---Original---
From: ***@***.***&gt;
Date: Tue, Feb 28, 2023 22:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Delay-Xili/SDNet] Waiting for the code (Issue #1)




 
looking forward to your codes

**Comment by liuyiming199721** [comment]
> 等候你的代码
Hello, can I make friends with you?

**Comment by liuyiming199721** [comment]
> 期也待代号，谢谢。

Hello, can I make friends with you?

**Comment by Alienge** [comment]
Hi All, I have reimplemented the code referring to the paper. The link is [TOYCODE](https://github.com/Alienge/ToySDNet). Before the official version appears, that plays toy for fun. If the official publish, I will delete the related code. I think there are some key questions that are not solved. For example, How to get the value of $t$. See #2 
To get the perfect code, I need all advice. 
If you are interested in this toy, I hope you give me some advice. Thx!!!

**Comment by kuaileyuandi** [comment]
Dear Delay-Xili.
       Thank you very much for making the code public, could you please provide a copy of the code for the SDNet application in the 1D dimension?

**Comment by Delay-Xili** [comment]
> Dear Delay-Xili. Thank you very much for making the code public, could you please provide a copy of the code for the SDNet application in the 1D dimension?

Hi,

Please refer to https://github.com/Delay-Xili/SDNet#sparse-coding-layer-for-1d-case.
