### ISSUE TITLE
Question on step parameter $t$

### ISSUE THREAD

**Issue by Alienge** [Delay-Xili/SDNet#2]
Recently， I tried to reimplement the code referring to this excellent work. But some confusion has troubled me. In your paper, $A$ denote convolution operation. For example, let $A$ $\in$ $R^{3\times 64 \times 7 \times 7}$. In calculating $t$ , you mentioned that the dominant eigenvalue is related to $t$. But referring to $A$, $A^{T}A$ $\in$ $R^{3\times64\times7\times7}$, the result of  dominant eigenvalue $\lambda \in R^{3\times64} $. 
Therefore $t\in R^{3\times64}$. But in Appendices A, the $tA^{\*}(x-A(y^{l}))$ in FISTA iteration has encountered the dimension error.
$$z^{L} = T_{\lambda t}{y^{l}+tA^{*}(x-A(y^{l}))}$$
I am looking forward to your reply. Thx.

**Comment by LEFTazs** [comment]
I think that the dominant eigenvalue must be a scalar, so t should also be a scalar, that's why you got a dimension error.

**Comment by Alienge** [comment]
> 

Yep. I think that should also be a scalar. But referring to power iteration to get the dominant eigenvalue, it carries out the following calculation to estimate the dominant eigenvector.
$$v^{k+1} = A^{T}(A(v^{k}))$$
The multi-dimensional kernel $A$ can be viewed as the number of $3 \times 64$ kernel($7\times7$). Therefore, $A^{T}A \in R^{3\times64\times7\times7}$. Or another option, the multi-dimensional kernel $A$ can be viewed as the number of $64$ kernel($3\times7\times7$). $A^{T}A \in R^{64\times64\times7\times7}$. Getting the dominant eigenvalue from above is a vector.
Or $A^{T}A \in R^{64\times64}$ get a scalar value. That is a good option to get a dominant eigenvalue? I confused.
So how about your views

**Comment by Alienge** [comment]
> I think that the dominant eigenvalue must be a scalar, so t should also be a scalar, that's why you got a dimension error.


Yep. I think that should also be a scalar. But referring to power iteration to get the dominant eigenvalue, it carries out the following calculation to estimate the dominant eigenvector.
$$v^{k+1} = A^{T}(A(v^{k}))$$
The multi-dimensional kernel $A$ can be viewed as the number of $3 \times 64$ kernel($7\times7$). Therefore, $A^{T}A \in R^{3\times64\times7\times7}$. Or another option, the multi-dimensional kernel $A$ can be viewed as the number of $64$ kernel($3\times7\times7$). $A^{T}A \in R^{64\times64\times7\times7}$. Getting the dominant eigenvalue from above is a vector.
Or $A^{T}A \in R^{64\times64}$ get a scalar value. That is a good option to get a dominant eigenvalue? I confused.
So how about your views

**Comment by liuyiming199721** [comment]
> 我认为主导特征值必须是标量，所以 t 也应该是标量，这就是为什么你有尺寸错误。

老哥，这个人是老外吧？方便交个朋友创个群嘛？

**Comment by Alienge** [comment]
> > 我认为主导特征值必须是标量，所以 t 也应该是标量，这就是为什么你有尺寸错误。
> 
> 老哥，这个人是老外吧？方便交个朋友创个群嘛？
yep, LEFTazs should not be Chinese. I release my code version referring to the paper. Any advice for it?

**Comment by liuyiming199721** [comment]
> > > 我认为主导特征值必须是标量，所以 t 也应该是标量，这就是为什么你有尺寸错误。
> > 
> > 
> > 老哥，这个人是老外吧？方便交个朋友创个群嘛？
> > yep, LEFTazs should not be Chinese. I release my code version referring to the paper. Any advice for it? The link is [CODE](https://github.com/Alienge/ToySDNet)

我怎么才能联系到您们？可以互相交换SDNet代码，留个facebook或者微信或者line或者电报或者其他的联系方式，我会想办法加你们的。谢谢

**Comment by liuyiming199721** [comment]
How can I get in touch with you? You can exchange SDNet codes with each other, leave a facebook or wechat or line or telegram or other contact information, I will find a way to add you. thank you

**Comment by liuyiming199721** [comment]
> 

How can I get in touch with you? You can exchange SDNet codes with each other, leave a facebook or wechat or line or telegram or other contact information, I will find a way to add you. thank you

**Comment by liuyiming199721** [comment]
> I think that the dominant eigenvalue must be a scalar, so t should also be a scalar, that's why you got a dimension error.

How can I get in touch with you? You can exchange SDNet codes with each other, leave a facebook or wechat or line or telegram or other contact information, I will find a way to add you. thank you

**Comment by Alienge** [comment]
I think the related [paper](https://arxiv.org/pdf/2006.16992.pdf) has the interpret the $A$. So the $t$ is solved. This issue will be closed soon.
